document.addEventListener('DOMContentLoaded', () => {
    const projects = [
        { title: 'Personal Finance Tracker', category: 'Web Development', description: 'A full-stack web app to track income, expenses, budgets and financial insights.', technologies: ['React', 'Node.js', 'MongoDB', 'Tailwind CSS'], author: 'Ajaykumar N', likes: 128, views: 2400 },
        { title: 'Railway Ticket Booking System', category: 'Web Development', description: 'A comprehensive railway ticket booking system with seat reservation and secure payments.', technologies: ['Java', 'JSP', 'MySQL', 'Bootstrap'], author: 'Varnika S', likes: 96, views: 1800 },
        { title: 'AI Vehicle Fault Detection', category: 'AI/ML', description: 'Real-time vehicle telemetry monitoring and AI-powered fault detection system.', technologies: ['Python', 'FastAPI', 'TensorFlow', 'PostgreSQL'], author: 'Vinovasri K', likes: 142, views: 3100 },
        { title: 'Habit Arena', category: 'Web Development', description: 'Gamified habit tracking app to build consistency and compete with friends.', technologies: ['React', 'Supabase', 'PostgreSQL', 'Tailwind CSS'], author: 'Meena R', likes: 87, views: 1200 },
        { title: 'MarketMind', category: 'Web Development', description: 'AI-powered stock market learning and trading simulator with real-time insights.', technologies: ['React', 'Node.js', 'Firebase', 'Groq AI'], author: 'Hari S', likes: 164, views: 2900 },
        { title: 'TaskFlow Pro', category: 'Tools', description: 'A productivity platform to manage tasks, teams and projects efficiently.', technologies: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL'], author: 'Kevin D', likes: 73, views: 950 }
    ];
    const grid = document.querySelector('.grid'); const search = document.querySelector('.filters input'); const categorySelect = document.querySelectorAll('.filters select')[0]; const sortSelect = document.querySelectorAll('.filters select')[1]; const categories = document.querySelectorAll('.cats button'); let category = 'All';
    const render = () => { const query = search.value.trim().toLowerCase(); let results = projects.filter(project => (category === 'All' || project.category === category) && `${project.title} ${project.category} ${project.technologies.join(' ')} ${project.author}`.toLowerCase().includes(query)); if (sortSelect.value === 'Most Liked') results.sort((a, b) => b.likes - a.likes); if (sortSelect.value === 'Most Viewed') results.sort((a, b) => b.views - a.views); grid.innerHTML = results.length ? results.map((project, index) => `<article><div class="pic p${index}">${project.title}</div><div class="body"><b>${project.category}</b><h2>${project.title}</h2><p>${project.description}</p><div class="tags">${project.technologies.map(technology => `<span>${technology}</span>`).join('')}</div><small>${project.author} · <button class="like" data-title="${project.title}" type="button">♡${project.likes}</button> · ◉${project.views}</small></div></article>`).join('') : '<p class="empty-state">No projects found.</p>'; grid.querySelectorAll('.like').forEach(button => button.addEventListener('click', () => { const project = projects.find(item => item.title === button.dataset.title); if (!button.classList.contains('liked')) { project.likes++; button.classList.add('liked'); button.textContent = `♥${project.likes}`; } })); };
    search?.addEventListener('input', render); sortSelect?.addEventListener('change', render); categorySelect?.addEventListener('change', () => { category = categorySelect.value === 'All Categories' ? 'All' : categorySelect.value; render(); }); categories.forEach(button => button.addEventListener('click', () => { categories.forEach(item => item.classList.remove('active')); button.classList.add('active'); category = button.textContent.trim(); render(); })); document.querySelector('.filters button')?.addEventListener('click', () => window.alert('Project submission will be connected to the backend later.')); render();
});
